import os, sys


# Compiler system environment paths.
sdk_base="C:\\Program Files\\Microsoft Platform SDK\\"

c_path ="%s\\Bin\\win64\\x86\\AMD64;"  % (sdk_base)
c_incl ="%s\\Include;%s\\INCLUDE\\crt" % (sdk_base, sdk_base)
c_lib  ="%s\\Lib\\AMD64;"              % (sdk_base)

# Common compiler switches for debug, release and profile environments:
# /nologo   No version and name banner.
# /W3       Warning level.
# /WX       Treat warnings as errors.
# /GR       Enable RTTI.
# /EHsc     Enable exception handling.
# /MT       Use multi-threaded run-time libraries (statically linked into the exe). Defines _MT.
# /O2       Fastest possible code.
# /Ox       Maximum optimizations
common_CXXFLAGS = '/nologo /W3 /WX /GR /EHsc /MT /O2 /Ox'

# Common link switches for both debug and release builds:
common_LINKFLAGS = '/nologo /incremental:no /MACHINE:AMD64'

# Compiler switches for release builds:
envRelease = Environment(CCFLAGS    = common_CXXFLAGS,
                         CPPDEFINES = Split('_CRT_SECURE_NO_DEPRECATE _CRT_NONSTDC_NO_DEPRECATE'),
                         LINKFLAGS  = common_LINKFLAGS)

envRelease['ENV']['PATH'] = c_path
envRelease['ENV']['INCLUDE'] = c_incl
envRelease['ENV']['LIB'] = c_lib

envRelease.SharedLibrary('sunflow',
                         'main.cpp',
                         SHLIBSUFFIX='.mll',
                         LIBS=Split("Foundation OpenMaya bufferoverflowU"),
                         LIBPATH=["C:\\Program Files\\Alias\\Maya8.0\\lib"],
                         CPPPATH=["C:\\Program Files\\Alias\\Maya8.0\\include"],
                         CPPDEFINES=Split('NDEBUG WIN32 _WINDOWS NT_PLUGIN REQUIRE_IOSTREAM Bits64_'),
                         LINKFLAGS=Split('/export:initializePlugin /export:uninitializePlugin'))
