//-
// ==========================================================================
// Copyright (C) 1995 - 2006 Autodesk, Inc. and/or its licensors.  All 
// rights reserved.
//
// The coded instructions, statements, computer programs, and/or related 
// material (collectively the "Data") in these files contain unpublished 
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its 
// licensors, which is protected by U.S. and Canadian federal copyright 
// law and by international treaties.
//
// The Data is provided for use exclusively by You. You have the right 
// to use, modify, and incorporate this Data into other products for 
// purposes authorized by the Autodesk software license agreement, 
// without fee.
//
// The copyright notices in the Software and this entire statement, 
// including the above license grant, this restriction and the 
// following disclaimer, must be included in all copies of the 
// Software, in whole or in part, and all derivative works of 
// the Software, unless such copies or derivative works are solely 
// in the form of machine-executable object code generated by a 
// source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. 
// AUTODESK DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED 
// WARRANTIES INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF 
// NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR 
// PURPOSE, OR ARISING FROM A COURSE OF DEALING, USAGE, OR 
// TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS LICENSORS 
// BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL, 
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK 
// AND/OR ITS LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY 
// OR PROBABILITY OF SUCH DAMAGES.
//
// ==========================================================================
//+

#include <maya/MPxNode.h>
#include <maya/MColor.h>

//
// DESCRIPTION:
///////////////////////////////////////////////////////
class sunflowShaderNode : public MPxNode
{
public:
                      sunflowShaderNode();
    virtual           ~sunflowShaderNode();

    virtual MStatus   compute( const MPlug&, MDataBlock& );
	virtual void      postConstructor();

	MColor getDiffuseComponent(MDataBlock& block);
	MColor getPhongComponent(MFloatVector &specular, float power, MDataBlock& block);	

    static void *     creator();
    static MStatus    initialize();
    static MTypeId    id;

private:
	static MObject aShader;	
	//PHONG SHADER	
	static MObject phong_specular;
	static MObject phong_power;
	static MObject phong_samples;
	//AMB_OCC SHADER	
	static MObject amb_dark;
	static MObject amb_samples;
	static MObject amb_maxdist;

	//GLASS SHADER
	static MObject glass_eta;
	static MObject glass_absorbtion_distance;
	static MObject glass_absorbtion_color;	

	//SHINY SHADER
	static MObject shiny_shiny;	

	//WARD SHADER
	static MObject ward_specular;
	static MObject ward_upower;
	static MObject ward_vpower;
	static MObject ward_samples;
	
	//UBER SHADER
	static MObject uber_diffuse_texture;
	static MObject uber_diffuse_blend;
	static MObject uber_specular;
	static MObject uber_specular_texture;
	static MObject uber_specular_blend;
	static MObject uber_gloss;
	static MObject uber_samples;

	static MObject aColor;    
	static MObject aPointCamera;
	static MObject aNormalCamera;
	static MObject aLightDirection;
	static MObject aLightIntensity;
    static MObject aPower;
    static MObject aSpecularity;
    static MObject aLightAmbient;
    static MObject aLightDiffuse;
    static MObject aLightSpecular;
    static MObject aLightShadowFraction;
    static MObject aPreShadowIntensity;
    static MObject aLightBlindData;
    static MObject aLightData;

    static MObject aRayOrigin;
    static MObject aRayDirection;

    static MObject aObjectId;
    static MObject aRaySampler;
    static MObject aRayDepth;

    static MObject aReflectGain;

	static MObject aTriangleNormalCamera;

	static MObject aOutColor;

};
